
name: smart_tourism_app
description: "A Smart Tourism Flutter App for Sri Lanka."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0        # Smooth animations
  unicons: ^2.0.1                # Modern line icons
  glassmorphism: ^3.0.0          # Glass effect UI

  # State Management & Logic
  provider: ^6.0.5
  dio: ^5.3.0                    # HTTP Client
  shared_preferences: ^2.2.0     # Local Storage (Auth Token)

  # Features
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  webview_flutter: ^4.4.1        # To show Tour Planner HTML
  intl: ^0.18.1                  # Date Formatting
  fl_chart: ^0.65.0              # Crowd Gauge/Charts
  cached_network_image: ^3.3.0   # Food Images

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
